language: node_js
node_js:
  - "9"

dist: trusty
sudo: false

branches:
  only:
    - master

cache:
  directories:
    - node_modules

before_script:
  - npm install -g @angular/cli

script:
  - ng lint
  - ng build --prod --base-href https://simonstadlinger.github.io/recipes/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/recipe
  on:
    branch: master
